@startuml
title Diagramme classes metier Simulation

class ModeleRobotPompier

class RobotPompier {
  +capaciteDeDeplacement
  +puissance
}

class Incendie {
  +position
}

class Carte {
}

class Zone {
  +difficulte
}

class Position

class Chemin {
  +double longeur
}

ModeleRobotPompier "1"--"*" RobotPompier
RobotPompier --> Incendie : Eteindre
Carte --> Incendie : Localiser
Carte --> RobotPompier : Localiser
Carte *- Zone
@enduml
